### ISSUE TITLE
retainedBlobCountLimit Issue

### ISSUE THREAD

**Issue by AJRussell** [chriswill/serilog-sinks-azureblobstorage#103]
Hi, 

When using the retainedBlobCountLimit parameter I get the below error after adding: Serilog.Debugging.SelfLog.Enable(msg => Debug.WriteLine(msg));

2023-06-14T11:37:20.7223638Z Caught exception while emitting to sink Serilog.Sinks.AzureBlobStorage.AzureBlobStorageSink: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Serilog.Sinks.AzureBlobStorage.AzureBlobProvider.DefaultCloudBlobProvider.DeleteArchivedBlobsAsync(BlobServiceClient blobServiceClient, String blobContainerName, String blobNameFormat, Int32 retainedBlobCountLimit)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Serilog.Sinks.AzureBlobStorage.AzureBlobProvider.DefaultCloudBlobProvider.DeleteArchivedBlobsAsync(BlobServiceClient blobServiceClient, String blobContainerName, String blobNameFormat, Int32 retainedBlobCountLimit)
   at Serilog.Sinks.AzureBlobStorage.AzureBlobStorageSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)

I have tried adding the 'Microsoft.Bcl.AsyncInterfaces dependency but apart from slowing down the Emit(LogEvent logEvent) method it still does not delete older blobs.

My App is .NET 6.0.

Any ideas on how to fix this?

Thanks in advance.

**Comment by chriswill** [comment]
I haven't seen that issue, but I did just publish a version of the sink that targets .net6 and also I revised the retainedBlobCountLimit area.  Please retry using version 4.0.0
