### ISSUE TITLE
Log file content not output when using Service Fabric

### ISSUE THREAD

**Issue by andyb70** [chriswill/serilog-sinks-azureblobstorage#35]
Whilst running my Service Fabric API within the remote cluster it fails to output any log information to the log file, however it does create the folder within the Blob container and it also creates the log file it just has no output.

I have added file logging to ensure that the log is being populated correctly and that log file when viewed on the VM does indeed contain log information.

If have configured the sink using the appsettings.json file, but I have also configured programmatically with the same result.

I have attached the settings file and I have also attached my StatelessService class to show how I am setting up the Logger.

[Identity.cs.txt](https://github.com/chriswill/serilog-sinks-azureblobstorage/files/3181513/Identity.cs.txt)

[appsettings.json.txt](https://github.com/chriswill/serilog-sinks-azureblobstorage/files/3181492/appsettings.json.txt)

Error message raised by Serilog.Debugging.SelfLog: -
2019-05-15T08:10:48.6968808Z Caught exception while emitting to sink Serilog.Sinks.AzureBlobStorage.AzureBlobStorageSink: System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Int64> Microsoft.Azure.Storage.Blob.CloudAppendBlob.AppendBlockAsync(System.IO.Stream)'.
   at Serilog.Sinks.AzureBlobStorage.DefaultAppendBlobBlockWriter.WriteBlocksToAppendBlobAsync(CloudAppendBlob cloudAppendBlob, IEnumerable`1 blocks)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Serilog.Sinks.AzureBlobStorage.DefaultAppendBlobBlockWriter.WriteBlocksToAppendBlobAsync(CloudAppendBlob cloudAppendBlob, IEnumerable`1 blocks)
   at Serilog.Sinks.AzureBlobStorage.AzureBlobStorageSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)

**Comment by andyb70** [comment]
I have downloaded the code and migrated the project to a Microsoft.NETCore.App 2.2.0 project and everything works fine.

**Comment by chriswill** [comment]
There is a new version 1.4.0 that I'd like you to try to see if it addresses this issue.  The new version compiles to .netstandard2.0.

If you would like to contribute fixes or changes there is no real protocol.  Just make a comment about your changes and contribute a pull request.  If your changes could benefit from unit tests (and many do), then please add corresponding unit tests as well.

thanks!
